days_of_week = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
hours = ["9-11", "11-13", "14-16", "16-18", "18-20"]
subjects = ["Artificial Inteligence", "Applied Project", "Mobile Programming", "Systems Integration",
"Embedded Systems", "Calculus", "Discrete Maths", "Informatics Labs", "Imperative Programming",
"Computers Architecture", "Object-Oriented Programming", "Statistics", "Physics", "Data Storage", "Software Engineering"]
classes = ["LESI1", "LESI2", "LESI3"]
teachers = ["Joaquim Gonçalves", "Patrícia Leite", "Nuno Mendes", "Luís Ferreira", "Paulo Macedo",
"Natália Rego", "Teresa Abreu", "Óscar Ribeiro", "Nuno Rodrigues", "Sandro Carvalho", "Andreia Monteiro",
"Daniel Miranda", "Paulo Teixeira", "Joaquim Silva"]
classrooms = ["Room T", "Room E", "Room C", "Room N", "Room IOT",
"Room Networking", "Room Auditorium", "Room Automation", "Room Electronics"]

# Define the start and goal states as dictionaries
start_state = {"day": "Monday", "hour": "9-11", "subject": "Artificial Inteligence", "class": "LESI3", "classroom": "Room T", "teacher": "Joaquim Gonçalves"}

actions = [

# -------------------------------------- Terceiro Ano ------------------------------------------------------------

{"day": "Monday", "hour": "9-11", "subject": "Applied Project", "class": "LESI3", "classroom": "Room E", "teacher": "Patrícia Leite", "cost": 1},
{"day": "Monday", "hour": "11-13", "subject": "Applied Project", "class": "LESI3", "classroom": "Room E", "teacher": "Patrícia Leite", "cost": 6},
{"day": "Monday", "hour": "14-16", "subject": "Applied Project", "class": "LESI3", "classroom": "Room E", "teacher": "Patrícia Leite", "cost": 10},
{"day": "Monday", "hour": "16-18", "subject": "Applied Project", "class": "LESI3", "classroom": "Room E", "teacher": "Patrícia Leite", "cost": 12},
{"day": "Monday", "hour": "18-20", "subject": "Applied Project", "class": "LESI3", "classroom": "Room E", "teacher": "Patrícia Leite", "cost": 20},
{"day": "Wednesday", "hour": "9-11", "subject": "Applied Project", "class": "LESI3", "classroom": "Room T", "teacher": "Patrícia Leite", "cost": 1},
{"day": "Wednesday", "hour": "11-13", "subject": "Applied Project", "class": "LESI3", "classroom": "Room T", "teacher": "Patrícia Leite", "cost": 6},
{"day": "Wednesday", "hour": "14-16", "subject": "Applied Project", "class": "LESI3", "classroom": "Room T", "teacher": "Patrícia Leite", "cost": 15},
{"day": "Wednesday", "hour": "16-18", "subject": "Applied Project", "class": "LESI3", "classroom": "Room T", "teacher": "Patrícia Leite", "cost": 16},
{"day": "Wednesday", "hour": "18-20", "subject": "Applied Project", "class": "LESI3", "classroom": "Room T", "teacher": "Patrícia Leite", "cost": 20},
{"day": "Friday", "hour": "9-11", "subject": "Applied Project", "class": "LESI3", "classroom": "Room T", "teacher": "Patrícia Leite", "cost": 2},
{"day": "Friday", "hour": "11-13", "subject": "Applied Project", "class": "LESI3", "classroom": "Room T", "teacher": "Patrícia Leite", "cost": 6},
{"day": "Friday", "hour": "14-16", "subject": "Applied Project", "class": "LESI3", "classroom": "Room T", "teacher": "Patrícia Leite", "cost": 15},
{"day": "Friday", "hour": "16-18", "subject": "Applied Project", "class": "LESI3", "classroom": "Room T", "teacher": "Patrícia Leite", "cost": 16},
{"day": "Friday", "hour": "18-20", "subject": "Applied Project", "class": "LESI3", "classroom": "Room T", "teacher": "Patrícia Leite", "cost": 20},
{"day": "Monday", "hour": "9-11", "subject": "Artificial Inteligence", "class": "LESI3", "classroom": "Room C", "teacher": "Joaquim Gonçalves", "cost": 3},
{"day": "Monday", "hour": "11-13", "subject": "Artificial Inteligence", "class": "LESI3", "classroom": "Room C", "teacher": "Joaquim Gonçalves", "cost": 5},
{"day": "Monday", "hour": "14-16", "subject": "Artificial Inteligence", "class": "LESI3", "classroom": "Room C", "teacher": "Joaquim Gonçalves", "cost": 10},
{"day": "Monday", "hour": "16-18", "subject": "Artificial Inteligence", "class": "LESI3", "classroom": "Room C", "teacher": "Joaquim Gonçalves", "cost": 15},
{"day": "Monday", "hour": "18-20", "subject": "Artificial Inteligence", "class": "LESI3", "classroom": "Room C", "teacher": "Joaquim Gonçalves", "cost": 20},
{"day": "Wednesday", "hour": "9-11", "subject": "Artificial Inteligence", "class": "LESI3", "classroom": "Room C", "teacher": "Joaquim Gonçalves", "cost": 1},
{"day": "Wednesday", "hour": "11-13", "subject": "Artificial Inteligence", "class": "LESI3", "classroom": "Room C", "teacher": "Joaquim Gonçalves", "cost": 6},
{"day": "Wednesday", "hour": "14-16", "subject": "Artificial Inteligence", "class": "LESI3", "classroom": "Room C", "teacher": "Joaquim Gonçalves", "cost": 9},
{"day": "Wednesday", "hour": "16-18", "subject": "Artificial Inteligence", "class": "LESI3", "classroom": "Room C", "teacher": "Joaquim Gonçalves", "cost": 15},
{"day": "Wednesday", "hour": "18-20", "subject": "Artificial Inteligence", "class": "LESI3", "classroom": "Room C", "teacher": "Joaquim Gonçalves", "cost": 20},
{"day": "Thursday", "hour": "9-11", "subject": "Artificial Inteligence", "class": "LESI3", "classroom": "Room C", "teacher": "Joaquim Gonçalves", "cost": 1},
{"day": "Thursday", "hour": "11-13", "subject": "Artificial Inteligence", "class": "LESI3", "classroom": "Room C", "teacher": "Joaquim Gonçalves", "cost": 6},
{"day": "Thursday", "hour": "14-16", "subject": "Artificial Inteligence", "class": "LESI3", "classroom": "Room C", "teacher": "Joaquim Gonçalves", "cost": 9},
{"day": "Thursday", "hour": "16-18", "subject": "Artificial Inteligence", "class": "LESI3", "classroom": "Room C", "teacher": "Joaquim Gonçalves", "cost": 15},
{"day": "Thursday", "hour": "18-20", "subject": "Artificial Inteligence", "class": "LESI3", "classroom": "Room C", "teacher": "Joaquim Gonçalves", "cost": 20},
{"day": "Monday", "hour": "9-11", "subject": "Systems Integration", "class": "LESI2", "classroom": "Room Auditorium", "teacher": "Luís Ferreira", "cost": 1},
{"day": "Monday", "hour": "11-13", "subject": "Systems Integration", "class": "LESI2", "classroom": "Room Auditorium", "teacher": "Luís Ferreira", "cost": 5},
{"day": "Monday", "hour": "14-16", "subject": "Systems Integration", "class": "LESI2", "classroom": "Room Auditorium", "teacher": "Luís Ferreira", "cost": 10},
{"day": "Monday", "hour": "16-18", "subject": "Systems Integration", "class": "LESI2", "classroom": "Room Auditorium", "teacher": "Luís Ferreira", "cost": 12},
{"day": "Monday", "hour": "18-20", "subject": "Systems Integration", "class": "LESI2", "classroom": "Room Auditorium", "teacher": "Luís Ferreira", "cost": 20},
{"day": "Thursday", "hour": "9-11", "subject": "Systems Integration", "class": "LESI2", "classroom": "Room Auditorium", "teacher": "Luís Ferreira", "cost": 2},
{"day": "Thursday", "hour": "11-13", "subject": "Systems Integration", "class": "LESI2", "classroom": "Room Auditorium", "teacher": "Luís Ferreira", "cost": 4},
{"day": "Thursday", "hour": "14-16", "subject": "Systems Integration", "class": "LESI2", "classroom": "Room Auditorium", "teacher": "Luís Ferreira", "cost": 12},
{"day": "Thursday", "hour": "16-18", "subject": "Systems Integration", "class": "LESI2", "classroom": "Room Auditorium", "teacher": "Luís Ferreira", "cost": 15},
{"day": "Thursday", "hour": "18-20", "subject": "Systems Integration", "class": "LESI2", "classroom": "Room Auditorium", "teacher": "Luís Ferreira", "cost": 20},
{"day": "Friday", "hour": "9-11", "subject": "Systems Integration", "class": "LESI2", "classroom": "Room Auditorium", "teacher": "Luís Ferreira", "cost": 2},
{"day": "Friday", "hour": "11-13", "subject": "Systems Integration", "class": "LESI2", "classroom": "Room Auditorium", "teacher": "Luís Ferreira", "cost": 4},
{"day": "Friday", "hour": "14-16", "subject": "Systems Integration", "class": "LESI2", "classroom": "Room Auditorium", "teacher": "Luís Ferreira", "cost": 12},
{"day": "Friday", "hour": "16-18", "subject": "Systems Integration", "class": "LESI2", "classroom": "Room Auditorium", "teacher": "Luís Ferreira", "cost": 15},
{"day": "Friday", "hour": "18-20", "subject": "Systems Integration", "class": "LESI2", "classroom": "Room Auditorium", "teacher": "Luís Ferreira", "cost": 20},
{"day": "Tuesday", "hour": "9-11", "subject": "Mobile Programming", "class": "LESI3", "classroom": "Room C", "teacher": "Nuno Mendes", "cost": 1},
{"day": "Tuesday", "hour": "11-13", "subject": "Mobile Programming", "class": "LESI3", "classroom": "Room C", "teacher": "Nuno Mendes", "cost": 5},
{"day": "Tuesday", "hour": "14-16", "subject": "Mobile Programming", "class": "LESI3", "classroom": "Room C", "teacher": "Nuno Mendes", "cost": 10},
{"day": "Tuesday", "hour": "16-18", "subject": "Mobile Programming", "class": "LESI3", "classroom": "Room C", "teacher": "Nuno Mendes", "cost": 16},
{"day": "Tuesday", "hour": "18-20", "subject": "Mobile Programming", "class": "LESI3", "classroom": "Room C", "teacher": "Nuno Mendes", "cost": 20},
{"day": "Thursday", "hour": "9-11", "subject": "Mobile Programming", "class": "LESI3", "classroom": "Room C", "teacher": "Nuno Mendes", "cost": 1},
{"day": "Thursday", "hour": "11-13", "subject": "Mobile Programming", "class": "LESI3", "classroom": "Room C", "teacher": "Nuno Mendes", "cost": 6},
{"day": "Thursday", "hour": "14-16", "subject": "Mobile Programming", "class": "LESI3", "classroom": "Room C", "teacher": "Nuno Mendes", "cost": 12},
{"day": "Thursday", "hour": "16-18", "subject": "Mobile Programming", "class": "LESI3", "classroom": "Room C", "teacher": "Nuno Mendes", "cost": 16},
{"day": "Thursday", "hour": "18-20", "subject": "Mobile Programming", "class": "LESI3", "classroom": "Room C", "teacher": "Nuno Mendes", "cost": 20},
{"day": "Monday", "hour": "9-11", "subject": "Mobile Programming", "class": "LESI3", "classroom": "Room C", "teacher": "Nuno Mendes", "cost": 1},
{"day": "Monday", "hour": "11-13", "subject": "Mobile Programming", "class": "LESI3", "classroom": "Room C", "teacher": "Nuno Mendes", "cost": 6},
{"day": "Monday", "hour": "14-16", "subject": "Mobile Programming", "class": "LESI3", "classroom": "Room C", "teacher": "Nuno Mendes", "cost": 12},
{"day": "Monday", "hour": "16-18", "subject": "Mobile Programming", "class": "LESI3", "classroom": "Room C", "teacher": "Nuno Mendes", "cost": 16},
{"day": "Monday", "hour": "18-20", "subject": "Mobile Programming", "class": "LESI3", "classroom": "Room C", "teacher": "Nuno Mendes", "cost": 20},
{"day": "Tuesday", "hour": "9-11", "subject": "Embedded Systems", "class": "LESI3", "classroom": "Room Electronics", "teacher": "Paulo Macedo", "cost": 1},
{"day": "Tuesday", "hour": "11-13", "subject": "Embedded Systems", "class": "LESI3", "classroom": "Room Electronics", "teacher": "Paulo Macedo", "cost": 5},
{"day": "Tuesday", "hour": "14-16", "subject": "Embedded Systems", "class": "LESI3", "classroom": "Room Electronics", "teacher": "Paulo Macedo", "cost": 9},
{"day": "Tuesday", "hour": "16-18", "subject": "Embedded Systems", "class": "LESI3", "classroom": "Room Electronics", "teacher": "Paulo Macedo", "cost": 15},
{"day": "Tuesday", "hour": "18-20", "subject": "Embedded Systems", "class": "LESI3", "classroom": "Room Electronics", "teacher": "Paulo Macedo", "cost": 20},
{"day": "Thursday", "hour": "9-11", "subject": "Embedded Systems", "class": "LESI3", "classroom": "Room Electronics", "teacher": "Paulo Macedo", "cost": 2},
{"day": "Thursday", "hour": "11-13", "subject": "Embedded Systems", "class": "LESI3", "classroom": "Room Electronics", "teacher": "Paulo Macedo", "cost": 4},
{"day": "Thursday", "hour": "14-16", "subject": "Embedded Systems", "class": "LESI3", "classroom": "Room Electronics", "teacher": "Paulo Macedo", "cost": 11},
{"day": "Thursday", "hour": "16-18", "subject": "Embedded Systems", "class": "LESI3", "classroom": "Room Electronics", "teacher": "Paulo Macedo", "cost": 12},
{"day": "Thursday", "hour": "18-20", "subject": "Embedded Systems", "class": "LESI3", "classroom": "Room Electronics", "teacher": "Paulo Macedo", "cost": 20},

# ----------------------------------------------- Segundo Ano ---------------------------------------------

{"day": "Monday", "hour": "9-11", "subject": "Object-Oriented Programming", "class": "LESI2", "classroom": "Room E", "teacher": "Luís Ferreira", "cost": 1},
{"day": "Monday", "hour": "11-13", "subject": "Object-Oriented Programming", "class": "LESI2", "classroom": "Room E", "teacher": "Luís Ferreira", "cost": 6},
{"day": "Monday", "hour": "14-16", "subject": "Object-Oriented Programming", "class": "LESI2", "classroom": "Room E", "teacher": "Luís Ferreira", "cost": 10},
{"day": "Monday", "hour": "16-18", "subject": "Object-Oriented Programming", "class": "LESI2", "classroom": "Room E", "teacher": "Luís Ferreira", "cost": 12},
{"day": "Monday", "hour": "18-20", "subject": "Object-Oriented Programming", "class": "LESI2", "classroom": "Room E", "teacher": "Luís Ferreira", "cost": 20},
{"day": "Tuesday", "hour": "9-11", "subject": "Object-Oriented Programming", "class": "LESI2", "classroom": "Room T", "teacher": "Luís Ferreira", "cost": 1},
{"day": "Tuesday", "hour": "11-13", "subject": "Object-Oriented Programming", "class": "LESI2", "classroom": "Room T", "teacher": "Luís Ferreira", "cost": 6},
{"day": "Tuesday", "hour": "14-16", "subject": "Object-Oriented Programming", "class": "LESI2", "classroom": "Room T", "teacher": "Luís Ferreira", "cost": 15},
{"day": "Tuesday", "hour": "16-18", "subject": "Object-Oriented Programming", "class": "LESI2", "classroom": "Room T", "teacher": "Luís Ferreira", "cost": 16},
{"day": "Tuesday", "hour": "18-20", "subject": "Object-Oriented Programming", "class": "LESI2", "classroom": "Room T", "teacher": "Luís Ferreira", "cost": 20},
{"day": "Friday", "hour": "9-11", "subject": "Object-Oriented Programming", "class": "LESI2", "classroom": "Room T", "teacher": "Luís Ferreira", "cost": 2},
{"day": "Friday", "hour": "11-13", "subject": "Object-Oriented Programming", "class": "LESI2", "classroom": "Room T", "teacher": "Luís Ferreira", "cost": 6},
{"day": "Friday", "hour": "14-16", "subject": "Object-Oriented Programming", "class": "LESI2", "classroom": "Room T", "teacher": "Luís Ferreira", "cost": 15},
{"day": "Friday", "hour": "16-18", "subject": "Object-Oriented Programming", "class": "LESI2", "classroom": "Room T", "teacher": "Luís Ferreira", "cost": 16},
{"day": "Friday", "hour": "18-20", "subject": "Object-Oriented Programming", "class": "LESI2", "classroom": "Room T", "teacher": "Luís Ferreira", "cost": 20},
{"day": "Tuesday", "hour": "9-11", "subject": "Statistics", "class": "LESI2", "classroom": "Room N", "teacher": "Andreia Monteiro", "cost": 3},
{"day": "Tuesday", "hour": "11-13", "subject": "Statistics", "class": "LESI2", "classroom": "Room N", "teacher": "Andreia Monteiro", "cost": 5},
{"day": "Tuesday", "hour": "14-16", "subject": "Statistics", "class": "LESI2", "classroom": "Room IOT", "teacher": "Andreia Monteiro", "cost": 11},
{"day": "Tuesday", "hour": "16-18", "subject": "Statistics", "class": "LESI2", "classroom": "Room T", "teacher": "Andreia Monteiro", "cost": 15},
{"day": "Tuesday", "hour": "18-20", "subject": "Statistics", "class": "LESI2", "classroom": "Room C", "teacher": "Andreia Monteiro", "cost": 20},
{"day": "Wednesday", "hour": "9-11", "subject": "Statistics", "class": "LESI2", "classroom": "Room E", "teacher": "Andreia Monteiro", "cost": 1},
{"day": "Wednesday", "hour": "11-13", "subject": "Statistics", "class": "LESI2", "classroom": "Room E", "teacher": "Andreia Monteiro", "cost": 6},
{"day": "Wednesday", "hour": "14-16", "subject": "Statistics", "class": "LESI2", "classroom": "Room E", "teacher": "Andreia Monteiro", "cost": 9},
{"day": "Wednesday", "hour": "16-18", "subject": "Statistics", "class": "LESI2", "classroom": "Room N", "teacher": "Andreia Monteiro", "cost": 15},
{"day": "Wednesday", "hour": "18-20", "subject": "Statistics", "class": "LESI2", "classroom": "Room T", "teacher": "Andreia Monteiro", "cost": 20},
{"day": "Thursday", "hour": "9-11", "subject": "Statistics", "class": "LESI2", "classroom": "Room E", "teacher": "Andreia Monteiro", "cost": 1},
{"day": "Thursday", "hour": "11-13", "subject": "Statistics", "class": "LESI2", "classroom": "Room E", "teacher": "Andreia Monteiro", "cost": 6},
{"day": "Thursday", "hour": "14-16", "subject": "Statistics", "class": "LESI2", "classroom": "Room N", "teacher": "Andreia Monteiro", "cost": 9},
{"day": "Thursday", "hour": "16-18", "subject": "Statistics", "class": "LESI2", "classroom": "Room IOT", "teacher": "Andreia Monteiro", "cost": 15},
{"day": "Thursday", "hour": "18-20", "subject": "Statistics", "class": "LESI2", "classroom": "Room C", "teacher": "Andreia Monteiro", "cost": 20},
{"day": "Tuesday", "hour": "9-11", "subject": "Physics", "class": "LESI2", "classroom": "Room IOT", "teacher": "Daniel Miranda", "cost": 1},
{"day": "Tuesday", "hour": "11-13", "subject": "Physics", "class": "LESI2", "classroom": "Room IOT", "teacher": "Daniel Miranda", "cost": 5},
{"day": "Tuesday", "hour": "14-16", "subject": "Physics", "class": "LESI2", "classroom": "Room IOT", "teacher": "Daniel Miranda", "cost": 10},
{"day": "Tuesday", "hour": "16-18", "subject": "Physics", "class": "LESI2", "classroom": "Room N", "teacher": "Daniel Miranda", "cost": 12},
{"day": "Tuesday", "hour": "18-20", "subject": "Physics", "class": "LESI2", "classroom": "Room N", "teacher": "Daniel Miranda", "cost": 20},
{"day": "Thursday", "hour": "9-11", "subject": "Physics", "class": "LESI2", "classroom": "Room T", "teacher": "Daniel Miranda", "cost": 2},
{"day": "Thursday", "hour": "11-13", "subject": "Physics", "class": "LESI2", "classroom": "Room N", "teacher": "Daniel Miranda", "cost": 4},
{"day": "Thursday", "hour": "14-16", "subject": "Physics", "class": "LESI2", "classroom": "Room C", "teacher": "Daniel Miranda", "cost": 12},
{"day": "Thursday", "hour": "16-18", "subject": "Physics", "class": "LESI2", "classroom": "Room C", "teacher": "Daniel Miranda", "cost": 15},
{"day": "Thursday", "hour": "18-20", "subject": "Physics", "class": "LESI2", "classroom": "Room E", "teacher": "Daniel Miranda", "cost": 20},
{"day": "Friday", "hour": "9-11", "subject": "Physics", "class": "LESI2", "classroom": "Room T", "teacher": "Daniel Miranda", "cost": 1},
{"day": "Friday", "hour": "11-13", "subject": "Physics", "class": "LESI2", "classroom": "Room T", "teacher": "Daniel Miranda", "cost": 4},
{"day": "Friday", "hour": "14-16", "subject": "Physics", "class": "LESI2", "classroom": "Room T", "teacher": "Daniel Miranda", "cost": 12},
{"day": "Friday", "hour": "16-18", "subject": "Physics", "class": "LESI2", "classroom": "Room T", "teacher": "Daniel Miranda", "cost": 15},
{"day": "Friday", "hour": "18-20", "subject": "Physics", "class": "LESI2", "classroom": "Room N", "teacher": "Daniel Miranda", "cost": 20},
{"day": "Monday", "hour": "9-11", "subject": "Data Storage", "class": "LESI2", "classroom": "Room E", "teacher": "Paulo Teixeira", "cost": 1},
{"day": "Monday", "hour": "11-13", "subject": "Data Storage", "class": "LESI2", "classroom": "Room E", "teacher": "Paulo Teixeira", "cost": 6},
{"day": "Monday", "hour": "14-16", "subject": "Data Storage", "class": "LESI2", "classroom": "Room C", "teacher": "Paulo Teixeira", "cost": 12},
{"day": "Monday", "hour": "16-18", "subject": "Data Storage", "class": "LESI2", "classroom": "Room T", "teacher": "Paulo Teixeira", "cost": 16},
{"day": "Monday", "hour": "18-20", "subject": "Data Storage", "class": "LESI2", "classroom": "Room T", "teacher": "Paulo Teixeira", "cost": 20},
{"day": "Wednesday", "hour": "9-11", "subject": "Data Storage", "class": "LESI2", "classroom": "Room N", "teacher": "Paulo Teixeira", "cost": 1},
{"day": "Wednesday", "hour": "11-13", "subject": "Data Storage", "class": "LESI2", "classroom": "Room T", "teacher": "Paulo Teixeira", "cost": 6},
{"day": "Wednesday", "hour": "14-16", "subject": "Data Storage", "class": "LESI2", "classroom": "Room T", "teacher": "Paulo Teixeira", "cost": 12},
{"day": "Wednesday", "hour": "16-18", "subject": "Data Storage", "class": "LESI2", "classroom": "Room IOT", "teacher": "Paulo Teixeira", "cost": 16},
{"day": "Wednesday", "hour": "18-20", "subject": "Data Storage", "class": "LESI2", "classroom": "Room C", "teacher": "Paulo Teixeira", "cost": 20},
{"day": "Friday", "hour": "9-11", "subject": "Data Storage", "class": "LESI2", "classroom": "Room E", "teacher": "Paulo Teixeira", "cost": 1},
{"day": "Friday", "hour": "11-13", "subject": "Data Storage", "class": "LESI2", "classroom": "Room E", "teacher": "Paulo Teixeira", "cost": 6},
{"day": "Friday", "hour": "14-16", "subject": "Data Storage", "class": "LESI2", "classroom": "Room E", "teacher": "Paulo Teixeira", "cost": 12},
{"day": "Friday", "hour": "16-18", "subject": "Data Storage", "class": "LESI2", "classroom": "Room N", "teacher": "Paulo Teixeira", "cost": 14},
{"day": "Friday", "hour": "18-20", "subject": "Data Storage", "class": "LESI2", "classroom": "Room N", "teacher": "Paulo Teixeira", "cost": 20},
{"day": "Wednesday", "hour": "9-11", "subject": "Software Engeneering", "class": "LESI2", "classroom": "Room N", "teacher": "Joaquim Silva", "cost": 1},
{"day": "Wednesday", "hour": "11-13", "subject": "Software Engeneering", "class": "LESI2", "classroom": "Room N", "teacher": "Joaquim Silva", "cost": 4},
{"day": "Wednesday", "hour": "14-16", "subject": "Software Engeneering", "class": "LESI2", "classroom": "Room N", "teacher": "Joaquim Silva", "cost": 9},
{"day": "Wednesday", "hour": "16-18", "subject": "Software Engeneering", "class": "LESI2", "classroom": "Room N", "teacher": "Joaquim Silva", "cost": 15},
{"day": "Wednesday", "hour": "18-20", "subject": "Software Engeneering", "class": "LESI2", "classroom": "Room N", "teacher": "Joaquim Silva", "cost": 20},
{"day": "Friday", "hour": "9-11", "subject": "Software Engeneering", "class": "LESI2", "classroom": "Room IOT", "teacher": "Joaquim Silva", "cost": 2},
{"day": "Friday", "hour": "11-13", "subject": "Software Engeneering", "class": "LESI2", "classroom": "Room IOT", "teacher": "Joaquim Silva", "cost": 4},
{"day": "Friday", "hour": "14-16", "subject": "Software Engeneering", "class": "LESI2", "classroom": "Room N", "teacher": "Joaquim Silva", "cost": 9},
{"day": "Friday", "hour": "16-18", "subject": "Software Engeneering", "class": "LESI2", "classroom": "Room T", "teacher": "Joaquim Silva", "cost": 11},
{"day": "Friday", "hour": "18-20", "subject": "Software Engeneering", "class": "LESI2", "classroom": "Room T", "teacher": "Joaquim Silva", "cost": 20},
{"day": "Thursday", "hour": "9-11", "subject": "Software Engeneering", "class": "LESI2", "classroom": "Room C", "teacher": "Joaquim Silva", "cost": 1},
{"day": "Thursday", "hour": "11-13", "subject": "Software Engeneering", "class": "LESI2", "classroom": "Room C", "teacher": "Joaquim Silva", "cost": 5},
{"day": "Thursday", "hour": "14-16", "subject": "Software Engeneering", "class": "LESI2", "classroom": "Room N", "teacher": "Joaquim Silva", "cost": 10},
{"day": "Thursday", "hour": "16-18", "subject": "Software Engeneering", "class": "LESI2", "classroom": "Room T", "teacher": "Joaquim Silva", "cost": 11},
{"day": "Thursday", "hour": "18-20", "subject": "Software Engeneering", "class": "LESI2", "classroom": "Room T", "teacher": "Joaquim Silva", "cost": 20},

# ----------------------------------------------- Primeiro Ano ---------------------------------------------

{"day": "Monday", "hour": "9-11", "subject": "Calculus", "class": "LESI1", "classroom": "Room T", "teacher": "Natália Rego", "cost": 1},
{"day": "Monday", "hour": "11-13", "subject": "Calculus", "class": "LESI1", "classroom": "Room T", "teacher": "Natália Rego", "cost": 6},
{"day": "Monday", "hour": "14-16", "subject": "Calculus", "class": "LESI1", "classroom": "Room T", "teacher": "Natália Rego", "cost": 10},
{"day": "Monday", "hour": "16-18", "subject": "Calculus", "class": "LESI1", "classroom": "Room T", "teacher": "Natália Rego", "cost": 12},
{"day": "Monday", "hour": "18-20", "subject": "Calculus", "class": "LESI1", "classroom": "Room T", "teacher": "Natália Rego", "cost": 20},
{"day": "Tuesday", "hour": "9-11", "subject": "Calculus", "class": "LESI1", "classroom": "Room IOT", "teacher": "Natália Rego", "cost": 1},
{"day": "Tuesday", "hour": "11-13", "subject": "Calculus", "class": "LESI1", "classroom": "Room IOT", "teacher": "Natália Rego", "cost": 4},
{"day": "Tuesday", "hour": "14-16", "subject": "Calculus", "class": "LESI1", "classroom": "Room IOT", "teacher": "Natália Rego", "cost": 15},
{"day": "Tuesday", "hour": "16-18", "subject": "Calculus", "class": "LESI1", "classroom": "Room N", "teacher": "Natália Rego", "cost": 16},
{"day": "Tuesday", "hour": "18-20", "subject": "Calculus", "class": "LESI1", "classroom": "Room N", "teacher": "Natália Rego", "cost": 20},
{"day": "Thursday", "hour": "9-11", "subject": "Calculus", "class": "LESI1", "classroom": "Room N", "teacher": "Natália Rego", "cost": 2},
{"day": "Thursday", "hour": "11-13", "subject": "Calculus", "class": "LESI1", "classroom": "Room C", "teacher": "Natália Rego", "cost": 6},
{"day": "Thursday", "hour": "14-16", "subject": "Calculus", "class": "LESI1", "classroom": "Room E", "teacher": "Natália Rego", "cost": 15},
{"day": "Thursday", "hour": "16-18", "subject": "Calculus", "class": "LESI1", "classroom": "Room E", "teacher": "Natália Rego", "cost": 16},
{"day": "Thursday", "hour": "18-20", "subject": "Calculus", "class": "LESI1", "classroom": "Room E", "teacher": "Natália Rego", "cost": 20},
{"day": "Tuesday", "hour": "9-11", "subject": "Discrete Maths", "class": "LESI1", "classroom": "Room C", "teacher": "Teresa Abreu", "cost": 3},
{"day": "Tuesday", "hour": "11-13", "subject": "Discrete Maths", "class": "LESI1", "classroom": "Room C", "teacher": "Teresa Abreu", "cost": 5},
{"day": "Tuesday", "hour": "14-16", "subject": "Discrete Maths", "class": "LESI1", "classroom": "Room N", "teacher": "Teresa Abreu", "cost": 11},
{"day": "Tuesday", "hour": "16-18", "subject": "Discrete Maths", "class": "LESI1", "classroom": "Room N", "teacher": "Teresa Abreu", "cost": 15},
{"day": "Tuesday", "hour": "18-20", "subject": "Discrete Maths", "class": "LESI1", "classroom": "Room C", "teacher": "Teresa Abreu", "cost": 20},
{"day": "Wednesday", "hour": "9-11", "subject": "Discrete Maths", "class": "LESI1", "classroom": "Room E", "teacher": "Teresa Abreu", "cost": 1},
{"day": "Wednesday", "hour": "11-13", "subject": "Discrete Maths", "class": "LESI1", "classroom": "Room E", "teacher": "Teresa Abreu", "cost": 6},
{"day": "Wednesday", "hour": "14-16", "subject": "Discrete Maths", "class": "LESI1", "classroom": "Room E", "teacher": "Teresa Abreu", "cost": 9},
{"day": "Wednesday", "hour": "16-18", "subject": "Discrete Maths", "class": "LESI1", "classroom": "Room N", "teacher": "Teresa Abreu", "cost": 15},
{"day": "Wednesday", "hour": "18-20", "subject": "Discrete Maths", "class": "LESI1", "classroom": "Room T", "teacher": "Teresa Abreu", "cost": 20},
{"day": "Thursday", "hour": "9-11", "subject": "Discrete Maths", "class": "LESI1", "classroom": "Room N", "teacher": "Teresa Abreu", "cost": 1},
{"day": "Thursday", "hour": "11-13", "subject": "Discrete Maths", "class": "LESI1", "classroom": "Room N", "teacher": "Teresa Abreu", "cost": 6},
{"day": "Thursday", "hour": "14-16", "subject": "Discrete Maths", "class": "LESI1", "classroom": "Room N", "teacher": "Teresa Abreu", "cost": 9},
{"day": "Thursday", "hour": "16-18", "subject": "Discrete Maths", "class": "LESI1", "classroom": "Room E", "teacher": "Teresa Abreu", "cost": 15},
{"day": "Thursday", "hour": "18-20", "subject": "Discrete Maths", "class": "LESI1", "classroom": "Room T", "teacher": "Teresa Abreu", "cost": 20},
{"day": "Tuesday", "hour": "9-11", "subject": "Informatic Labs", "class": "LESI1", "classroom": "Room C", "teacher": "Nuno Rodrigues", "cost": 1},
{"day": "Tuesday", "hour": "11-13", "subject": "Informatic Labs", "class": "LESI1", "classroom": "Room E", "teacher": "Nuno Rodrigues", "cost": 5},
{"day": "Tuesday", "hour": "14-16", "subject": "Informatic Labs", "class": "LESI1", "classroom": "Room E", "teacher": "Nuno Rodrigues", "cost": 10},
{"day": "Tuesday", "hour": "16-18", "subject": "Informatic Labs", "class": "LESI1", "classroom": "Room T", "teacher": "Nuno Rodrigues", "cost": 12},
{"day": "Tuesday", "hour": "18-20", "subject": "Informatic Labs", "class": "LESI1", "classroom": "Room N", "teacher": "Nuno Rodrigues", "cost": 20},
{"day": "Monday", "hour": "9-11", "subject": "Informatic Labs", "class": "LESI1", "classroom": "Room Networking", "teacher": "Nuno Rodrigues", "cost": 2},
{"day": "Monday", "hour": "11-13", "subject": "Informatic Labs", "class": "LESI1", "classroom": "Room Networking", "teacher": "Nuno Rodrigues", "cost": 4},
{"day": "Monday", "hour": "14-16", "subject": "Informatic Labs", "class": "LESI1", "classroom": "Room Networking", "teacher": "Nuno Rodrigues", "cost": 12},
{"day": "Monday", "hour": "16-18", "subject": "Informatic Labs", "class": "LESI1", "classroom": "Room Networking", "teacher": "Nuno Rodrigues", "cost": 15},
{"day": "Monday", "hour": "18-20", "subject": "Informatic Labs", "class": "LESI1", "classroom": "Room Networking", "teacher": "Nuno Rodrigues", "cost": 20},
{"day": "Friday", "hour": "9-11", "subject": "Informatic Labs", "class": "LESI1", "classroom": "Room T", "teacher": "Nuno Rodrigues", "cost": 1},
{"day": "Friday", "hour": "11-13", "subject": "Informatic Labs", "class": "LES11", "classroom": "Room C", "teacher": "Nuno Rodrigues", "cost": 4},
{"day": "Friday", "hour": "14-16", "subject": "Informatic Labs", "class": "LESI1", "classroom": "Room T", "teacher": "Nuno Rodrigues ", "cost": 12},
{"day": "Friday", "hour": "16-18", "subject": "Informatic Labs", "class": "LESI1", "classroom": "Room C", "teacher": "Nuno Rodrigues", "cost": 15},
{"day": "Friday", "hour": "18-20", "subject": "Informatic Labs", "class": "LESI1", "classroom": "Room T", "teacher": "Nuno Rodrigues", "cost": 20},
{"day": "Monday", "hour": "9-11", "subject": "Imperative Programming", "class": "LESI1", "classroom": "Room E", "teacher": "Óscar Ribeiro", "cost": 1},
{"day": "Monday", "hour": "11-13", "subject": "Imperative Programming", "class": "LESI1", "classroom": "Room E", "teacher": "Óscar Ribeiro", "cost": 4},
{"day": "Monday", "hour": "14-16", "subject": "Imperative Programming", "class": "LESI1", "classroom": "Room C", "teacher": "Óscar Ribeiro", "cost": 8},
{"day": "Monday", "hour": "16-18", "subject": "Imperative Programming", "class": "LESI1", "classroom": "Room T", "teacher": "Óscar Ribeiro", "cost": 16},
{"day": "Monday", "hour": "18-20", "subject": "Imperative Programming", "class": "LESI1", "classroom": "Room T", "teacher": "Óscar Ribeiro", "cost": 20},
{"day": "Tuesday", "hour": "9-11", "subject": "Imperative Programming", "class": "LESI1", "classroom": "Room IOT", "teacher": "Óscar Ribeiro", "cost": 1},
{"day": "Tuesday", "hour": "11-13", "subject": "Imperative Programming", "class": "LESI1", "classroom": "Room IOT", "teacher": "Óscar Ribeiro", "cost": 4},
{"day": "Tuesday", "hour": "14-16", "subject": "Imperative Programming", "class": "LESI1", "classroom": "Room T", "teacher": "Óscar Ribeiro", "cost": 12},
{"day": "Tuesday", "hour": "16-18", "subject": "Imperative Programming", "class": "LESI1", "classroom": "Room IOT", "teacher": "Óscar Ribeiro", "cost": 16},
{"day": "Tuesday", "hour": "18-20", "subject": "Imperative Programming", "class": "LESI1", "classroom": "Room C", "teacher": "Óscar Ribeiro", "cost": 20},
{"day": "Thursday", "hour": "9-11", "subject": "Imperative Programming", "class": "LESI1", "classroom": "Room E", "teacher": "Óscar Ribeiro", "cost": 1},
{"day": "Thursday", "hour": "11-13", "subject": "Imperative Programming", "class": "LESI1", "classroom": "Room E", "teacher": "Óscar Ribeiro", "cost": 3},
{"day": "Thursday", "hour": "14-16", "subject": "Imperative Programming", "class": "LESI1", "classroom": "Room E", "teacher": "Óscar Ribeiro", "cost": 8},
{"day": "Thursday", "hour": "16-18", "subject": "Imperative Programming", "class": "LESI1", "classroom": "Room N", "teacher": "Óscar Ribeiro", "cost": 14},
{"day": "Thursday", "hour": "18-20", "subject": "Imperative Programming", "class": "LESI1", "classroom": "Room N", "teacher": "Óscar Ribeiro", "cost": 20},
{"day": "Monday", "hour": "9-11", "subject": "Computers Architeture", "class": "LESI1", "classroom": "Room Electronics", "teacher": "Sandro Carvalho", "cost": 1},
{"day": "Monday", "hour": "11-13", "subject": "Computers Architeture", "class": "LESI1", "classroom": "Room Electronics", "teacher": "Sandro Carvalho", "cost": 4},
{"day": "Monday", "hour": "14-16", "subject": "Computers Architeture", "class": "LESI1", "classroom": "Room Electronics", "teacher": "Sandro Carvalho", "cost": 8},
{"day": "Monday", "hour": "16-18", "subject": "Computers Architeture", "class": "LESI1", "classroom": "Room Electronics", "teacher": "Sandro Carvalho", "cost": 15},
{"day": "Monday", "hour": "18-20", "subject": "Computers Architeture", "class": "LESI1", "classroom": "Room Electronics", "teacher": "Sandro Carvalho", "cost": 20},
{"day": "Friday", "hour": "9-11", "subject": "Computers Architeture", "class": "LESI1", "classroom": "Room Electronics", "teacher": "Sandro Carvalho", "cost": 1},
{"day": "Friday", "hour": "11-13", "subject": "Computers Architeture", "class": "LESI1", "classroom": "Room Electronics", "teacher": "Sandro Carvalho", "cost": 6},
{"day": "Friday", "hour": "14-16", "subject": "Computers Architeture", "class": "LESI1", "classroom": "Room Electronics", "teacher": "Sandro Carvalho", "cost": 9},
{"day": "Friday", "hour": "16-18", "subject": "Computers Architeture", "class": "LESI1", "classroom": "Room Electronics", "teacher": "Sandro Carvalho", "cost": 11},
{"day": "Friday", "hour": "18-20", "subject": "Computers Architeture", "class": "LESI1", "classroom": "Room Electronics", "teacher": "Sandro Carvalho", "cost": 20},
{"day": "Thursday", "hour": "9-11", "subject": "Computers Architeture", "class": "LESI1", "classroom": "Room Electronics", "teacher": "Sandro Carvalho", "cost": 1},
{"day": "Thursday", "hour": "11-13", "subject": "Computers Architeture", "class": "LESI1", "classroom": "Room Electronics", "teacher": "Sandro Carvalho", "cost": 5},
{"day": "Thursday", "hour": "14-16", "subject": "Computers Architeture", "class": "LESI1", "classroom": "Room Electronics", "teacher": "Sandro Carvalho", "cost": 8},
{"day": "Thursday", "hour": "16-18", "subject": "Computers Architeture", "class": "LESI1", "classroom": "Room Electronics", "teacher": "Sandro Carvalho", "cost": 11},
{"day": "Thursday", "hour": "18-20", "subject": "Computers Architeture", "class": "LESI1", "classroom": "Room Electronics", "teacher": "Sandro Carvalho", "cost": 20}
]

goal_states = [
    {"day": "Monday", "hour": "9-11", "subject": "Applied Project", "class": "LESI2", "classroom": "Room E", "teacher": "Patrícia Leite"},
    {"day": "Friday", "hour": "11-13", "subject": "Mobile Programming", "class": "LESI3", "classroom": "Room C", "teacher": "Nuno Mendes"},
    {"day": "Friday", "hour": "16-18", "subject": "Discrete Maths", "class": "LESI1", "classroom": "Room E", "teacher": "Teresa Abreu"}
    ]

